import Head from "next/head";
import Image from "next/image";
import styles from "../../src/styles/Home.module.css";

import myAvatar from "../assets/meuavatar.png"

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Christian Martins</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Christian Martins</h1>
        <h2>Desenvolvedor Front-end</h2>
        <Image
          src={myAvatar}
          alt="Meu avatar"
          width={200}
          height={200}
        />
      </main>
    </div>
  );
}
